### ISSUE TITLE
can't open file './compile_single.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by chiefdfo** [tjclement/pokemongo-bot#3]
Good Evening. 

first i copied the protoc tool to the Python35/scripts Folder, which is in $PATH.
Then i installed the requirements with the command explained. 
Then i tried `sh scripts/compile_proto.sh` and it gave following error message:

> C:\Program Files\Python35\python.exe: can't open file './compile_single.py': [Errno 2] No such file or directory

i'm using Windows10 64 Bit. 

Thanks! :smiley:

**Comment by tjclement** [comment]
Looks like you didn't clone the repository with the protos_repository submodule quite right, I'm assuming your protos_repository folder is completely empty?

For info on how to clone a project with Git submodules, [have a look at this].(http://stackoverflow.com/a/4438292)
